##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  spring配置  ###################
spring:
  session:
    store-type: none
  profiles:
    active: dev # 激活dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: true #是否开启开发者工具（true/false）
     # additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
###################  guns配置  ###################
guns:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: true #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒



###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false




###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.common.persistence.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


  #################################  分销配置#####################################

dist:
  jwt:
    secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
    account: xiaojiang
    isUse: false
  member:
    suffix: member
  profit:
    isUse: true
    userModel: rate
    fix: 1000
    rate: 1


######################## 加解密配置########################################
encrypt:
  name: DES  #保留 ，待扩展
  key: a_stex_0